
- name: create main directories
  file:
    dest: /jarry/etc/
    mode: 0775
    recurse: yes
    state: directory

- name: insert docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /jarry/etc/docker-compose.yml
    mode: 0755

- name: login to registry
  shell: "docker login {{ service_install_run_registry_url }} -u {{ service_install_run_registry_user }} -p {{ service_install_run_registry_password }}"

- name: run docker-compose
  shell: docker-compose -f /jarry/etc/docker-compose.yml down

- name: run docker-compose
  shell: docker-compose -f /jarry/etc/docker-compose.yml up -d

- name: wait for instance
  uri:
    url: 'http://127.0.0.1:80'
    method: GET
  register: result


